### ISSUE TITLE
Fail to upgrade from v2.0.0 to v2.0.3

### ISSUE THREAD

**Issue by Darren** [pingcap/pd#1107]
trying to upgrade pd-server from v2.0.0 to v2.0.3, got this panic

It seems that there's some change in the vendored boltdb that causes this

```go
panic: runtime error: index out of range

goroutine 115 [running]:
github.com/pingcap/pd/vendor/github.com/coreos/bbolt.(*DB).page(...)
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/bbolt/db.go:793
github.com/pingcap/pd/vendor/github.com/coreos/bbolt.Open(0xc4204782e0, 0x16, 0x180, 0xc4200ade10, 0x5a790e, 0xc4204782e0, 0x16)
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/bbolt/db.go:237 +0x655
github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend.newBackend(0xc4204782e0, 0x16, 0x5f5e100, 0x2710, 0x280000000, 0x2)
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:129 +0x9d
github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend.New(0xc4204782e0, 0x16, 0x5f5e100, 0x2710, 0x280000000, 0xc42003e070, 0xc42003e000)
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:113 +0x48
github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver.newBackend(0xc4203c1800, 0x432dd8, 0xfcd840)
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/backend.go:36 +0x17d
github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver.openBackend.func1(0xc4202f6180, 0xc4203c1800)
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/backend.go:56 +0x2b
created by github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver.openBackend
	/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/backend.go:55 +0x9f
```

How can I upgrade pd-server safely?

**Comment by nolouch** [comment]
@Darren Have you ever used master version? now the PD cannot downgrade from master to v2.0.x, that mostly causes of this log. you can check the log to see if you have used the master branch. if yes, you should continue to use the master version.

**Comment by Darren** [comment]
@nolouch 

the current version I am using is(which does not panic):

```
Release Version: v2.0.0-rc.4-24-g2350c17
Git Commit Hash: 2350c17e1062b506ce276f419eec0943aabdd511
Git Branch: heads/v2.0.0
UTC Build Time:  2018-06-12 03:15:03
```

IIRC I have not used master branch for several months but switch between the  v2.0.x  tags for several times, here's the revisions I tried this morning:

```
2018/06/12 10:56:17.016 util.go:63: [info] Release Version: v2.0.3
2018/06/12 10:56:17.016 util.go:64: [info] Git Commit Hash: 49ef99b6faa6d8cb6c797f74b118ded03253c898
2018/06/12 10:56:17.016 util.go:65: [info] Git Branch: release-2.0
2018/06/12 11:03:05.676 util.go:63: [info] Release Version: v2.0.0-rc.4-24-g2350c17
2018/06/12 11:03:05.676 util.go:64: [info] Git Commit Hash: 2350c17e1062b506ce276f419eec0943aabdd511
2018/06/12 11:03:05.676 util.go:65: [info] Git Branch: heads/v2.0.0
2018/06/12 11:07:52.960 util.go:63: [info] Release Version: v2.0.3
2018/06/12 11:07:52.960 util.go:64: [info] Git Commit Hash: 49ef99b6faa6d8cb6c797f74b118ded03253c898
2018/06/12 11:07:52.960 util.go:65: [info] Git Branch: heads/v2.0.3
2018/06/12 11:10:40.013 util.go:63: [info] Release Version: v2.0.3
2018/06/12 11:10:40.013 util.go:64: [info] Git Commit Hash: 49ef99b6faa6d8cb6c797f74b118ded03253c898
2018/06/12 11:10:40.013 util.go:65: [info] Git Branch: heads/v2.0.3
2018/06/12 11:14:11.965 util.go:63: [info] Release Version: v2.0.3
2018/06/12 11:14:11.965 util.go:64: [info] Git Commit Hash: 49ef99b6faa6d8cb6c797f74b118ded03253c898
2018/06/12 11:14:11.965 util.go:65: [info] Git Branch: heads/v2.0.2
2018/06/12 11:15:33.457 util.go:63: [info] Release Version: v2.0.0-rc.4-24-g2350c17
2018/06/12 11:15:33.457 util.go:64: [info] Git Commit Hash: 2350c17e1062b506ce276f419eec0943aabdd511
2018/06/12 11:15:33.457 util.go:65: [info] Git Branch: heads/v2.0.0
```

**Comment by nolouch** [comment]
@Darren The commit `2350c1` is in the master branch, not in the v2.0.0. There must be something. and where you got it?

**Comment by Darren** [comment]
@nolouch 

I see. my mistake.
