### ISSUE TITLE
server panics when accessing '/health'

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#1185]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- Kill a follower PD node.
- Use pd-ctl to check health status

2. What did you expect to see?
health information

3. What did you see instead?
panic error:
```
 pd-ctl -u http://XXXXX:3383 
 » health
 [500] PANIC: runtime error: invalid memory address or nil pointer dereference
 goroutine 113377387 [running]:
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7fb806d50f78, 0xc420acb8a0, 0xc420326d70, 0xc42227a500)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/recovery.go:159 +0xef
 panic(0xe00c20, 0x157ab70)
  /usr/local/go/src/runtime/panic.go:505 +0x229
 github.com/pingcap/pd/server/api.(*healthHandler).ServeHTTP(0xc4203f28e0, 0x7fb806d50f78, 0xc420acb8a8, 0xc42227aa00)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/api/health.go:63 +0x96
 github.com/pingcap/pd/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203807e0, 0x7fb806d50f78, 0xc420acb8a8, 0xc42227aa00)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/gorilla/mux/mux.go:159 +0xed
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.Wrap.func1(0x7fb806d50f78, 0xc420acb8a8, 0xc42227a700, 0xc422efa420)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:46 +0x4d
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc4203c7b20, 0x7fb806d50f78, 0xc420acb8a8, 0xc42227a700, 0xc422efa420)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:29 +0x4e
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x1040760, 0xc4203c7b20, 0xc4203c7b80, 0x7fb806d50f78, 0xc420acb8a8, 0xc42227a700)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:38 +0xa5
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fb806d50f78, 0xc420acb8a8, 0xc42227a700)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:38 +0x60
 github.com/pingcap/pd/server/api.(*redirector).ServeHTTP(0xc42032a0c0, 0x7fb806d50f78, 0xc420acb8a8, 0xc42227a700, 0xc422efa400)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/api/redirector.go:45 +0x512
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x103e7e0, 0xc42032a0c0, 0xc4203c7b60, 0x7fb806d50f78, 0xc420acb8a8, 0xc42227a700)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:38 +0xa5
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc420402b70, 0x7fb806d50f78, 0xc420acb8a0, 0xc42227a700)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:96 +0xf2
 github.com/pingcap/pd/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203800e0, 0x7fb806d50f78, 0xc420acb8a0, 0xc42227a700)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/gorilla/mux/mux.go:159 +0xed
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.Wrap.func1(0x7fb806d50f78, 0xc420acb8a0, 0xc42227a500, 0xc422efa3e0)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:46 +0x4d
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc4203c7bc0, 0x7fb806d50f78, 0xc420acb8a0, 0xc42227a500, 0xc422efa3e0)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:29 +0x4e
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x1040760, 0xc4203c7bc0, 0xc4203c7c20, 0x7fb806d50f78, 0xc420acb8a0, 0xc42227a500)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:38 +0xa5
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7fb806d50f78, 0xc420acb8a0, 0xc42227a500)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:38 +0x60
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc420326d70, 0x7fb806d50f78, 0xc420acb8a0, 0xc42227a500, 0xc422efa3c0)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/recovery.go:193 +0x8c
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x103f460, 0xc420326d70, 0xc4203c7c00, 0x7fb806d50f78, 0xc420acb8a0, 0xc42227a500)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:38 +0xa5
 github.com/pingcap/pd/vendor/github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc42031f290, 0x104bd80, 0xc422284620, 0xc42227a500)
  /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/urfave/negroni/negroni.go:96 +0xf2
 net/http.(*ServeMux).ServeHTTP(0xc4222990b0, 0x104bd80, 0xc422284620, 0xc42227a500)
  /usr/local/go/src/net/http/server.go:2337 +0x130
 net/http.serverHandler.ServeHTTP(0xc421eee750, 0x104bd80, 0xc422284620, 0xc42227a500)
  /usr/local/go/src/net/http/server.go:2694 +0xbc
 net/http.(*conn).serve(0xc4203520a0, 0x104ce40, 0xc4239bf140)
  /usr/local/go/src/net/http/server.go:1830 +0x651
 created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2795 +0x27b
```

4. What version of PD are you using (`pd-server -V`)?

**Comment by overvenus** [comment]
What's the status of this issue?

**Comment by rleungx** [comment]
I think this problem is no longer existed, close it for now. Feel free to reopen it if there is still a problem.
