### ISSUE TITLE
Goroutine cannot exit, causing leader election blocked

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#1569]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

goroutine 622 
```
goroutine 622 [semacquire, 768 minutes]:
sync.runtime_Semacquire(0xc000410598)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000410590)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/pingcap/pd/server.(*RaftCluster).stop(0xc000410540)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/cluster.go:151 +0x82
github.com/pingcap/pd/server.(*Server).stopRaftCluster(0xc00026c600)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/server.go:412 +0x32
github.com/pingcap/pd/server.(*Server).campaignLeader(0xc00026c600, 0x1341f40, 0xc005c36b20)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/leader.go:279 +0xe0c
github.com/pingcap/pd/server.(*Server).leaderLoop(0xc00026c600)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/leader.go:115 +0x379
created by github.com/pingcap/pd/server.(*Server).startServerLoop
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/server.go:301 +0xa2
```
goroutine 867:
```
goroutine 867 [select, 105153 minutes]:
net/http.(*persistConn).roundTrip(0xc003ee1320, 0xc00a64e840, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:2101 +0x56a
net/http.(*Transport).roundTrip(0xc00037b200, 0xc003c08c00, 0x203002, 0xc003d9baa0, 0x72757a)
	/usr/local/go/src/net/http/transport.go:465 +0x9b1
net/http.(*Transport).RoundTrip(0xc00037b200, 0xc003c08c00, 0xc00037b200, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc003c08c00, 0x13427e0, 0xc00037b200, 0x0, 0x0, 0x0, 0xc009b50688, 0xc00a64e6c0, 0xc003d9bb30, 0x1)
	/usr/local/go/src/net/http/client.go:250 +0x14b
net/http.(*Client).send(0xc00046a1e0, 0xc003c08c00, 0x0, 0x0, 0x0, 0xc009b50688, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc00046a1e0, 0xc003c08c00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x2a8
net/http.(*Client).Do(0xc00046a1e0, 0xc003c08c00, 0xc0087f3bc0, 0x1d, 0x0)
	/usr/local/go/src/net/http/client.go:509 +0x35
net/http.(*Client).Get(0xc00046a1e0, 0xc0087f3bc0, 0x1d, 0x2, 0x2, 0xc0087f3bc0)
	/usr/local/go/src/net/http/client.go:398 +0x9d
github.com/pingcap/pd/server.(*Server).CheckHealth(0xc00026c600, 0xc007620840, 0x8, 0x8, 0x0)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/server.go:715 +0x185
github.com/pingcap/pd/server.(*RaftCluster).collectHealthStatus(0xc000410540)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/cluster.go:533 +0x112
github.com/pingcap/pd/server.(*RaftCluster).collectMetrics(0xc000410540)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/cluster.go:524 +0x144
github.com/pingcap/pd/server.(*RaftCluster).runBackgroundJobs(0xc000410540, 0xdf8475800)
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/cluster.go:557 +0xf7
created by github.com/pingcap/pd/server.(*RaftCluster).start
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/cluster.go:122 +0x544

```

2. What did you expect to see?
should elect a new leader

3. What did you see instead?
leader election block.

4. What version of PD are you using (`pd-server -V`)?
v2.1.2

**Comment by nolouch** [comment]
fixed by: https://github.com/pingcap/pd/pull/1515. we need cherry pick @rleungx

**Comment by siddontang** [comment]
can we reproduce this problem?
