### ISSUE TITLE
panic in negroni when visit /pd/api/v1/version

### ISSUE THREAD

**Issue by leoppro** [pingcap/pd#1764]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

run this shell script:
```
    echo "Starting PD..."
    pd-server \
        --client-urls http://127.0.0.1:2379 \
        --log-file "$OUT_DIR/pd.log" \
        --data-dir "$OUT_DIR/pd" &

    # wait until PD is online...
    while ! curl -o /dev/null -sf http://127.0.0.1:2379/pd/api/v1/version; do
        sleep 0.2
    done
```

2. What did you expect to see?
no panic

3. What did you see instead?
```
Starting PD...
[negroni] PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 167 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x5c11350, 0xc0000ac188, 0xc0000bb310, 0xc0006f0100)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/recovery.go:159 +0xcb
panic(0x1d91660, 0x2b1c9d0)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/pd/server/member.(*Member).GetLeader(0x0, 0xc000368bd0)
        /Users/leoppro/Code/pd/server/member/leader.go:103 +0x26
github.com/pingcap/pd/server/api.(*redirector).ServeHTTP(0xc00000e7c8, 0x5c11350, 0xc0000ac190, 0xc000266600, 0xc00019af20)
        /Users/leoppro/Code/pd/server/api/redirector.go:60 +0x49b
github.com/urfave/negroni.middleware.ServeHTTP(0x215fca0, 0xc00000e7c8, 0xc0003eefa0, 0x5c11350, 0xc0000ac190, 0xc000266600)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0003e9b00, 0x5c11350, 0xc0000ac188, 0xc000266600)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0xec
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002551f0, 0x5c11350, 0xc0000ac188, 0xc000266600)
        /Users/leoppro/GoPath/pkg/mod/github.com/gorilla/mux@v1.6.1/mux.go:159 +0x105
github.com/urfave/negroni.Wrap.func1(0x5c11350, 0xc0000ac188, 0xc0006f0100, 0xc00019af00)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0003ef000, 0x5c11350, 0xc0000ac188, 0xc0006f0100, 0xc00019af00)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x2162080, 0xc0003ef000, 0xc0003ef060, 0x5c11350, 0xc0000ac188, 0xc0006f0100)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc0000bb310, 0x5c11350, 0xc0000ac188, 0xc0006f0100, 0xc00019aee0)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/recovery.go:193 +0x8c
github.com/urfave/negroni.middleware.ServeHTTP(0x2160160, 0xc0000bb310, 0xc0003ef040, 0x5c11350, 0xc0000ac188, 0xc0006f0100)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc000233950, 0x21808c0, 0xc00076c000, 0xc0006f0100)
        /Users/leoppro/GoPath/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0xec
net/http.(*ServeMux).ServeHTTP(0xc00066e980, 0x21808c0, 0xc00076c000, 0xc0006f0100)
        /usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2375 +0x1d6
go.etcd.io/etcd/embed.(*accessController).ServeHTTP(0xc00030b020, 0x21808c0, 0xc00076c000, 0xc0006f0100)
        /Users/leoppro/GoPath/pkg/mod/go.etcd.io/etcd@v0.0.0-20190320044326-77d4b742cdbf/embed/serve.go:359 +0x1b7
net/http.serverHandler.ServeHTTP(0xc0002e3110, 0x21808c0, 0xc00076c000, 0xc0006f0100)
        /usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000768000, 0x2185d00, 0xc0001be300)
        /usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2884 +0x2f4
```

4. What version of PD are you using (`pd-server -V`)?

```
Release Version: v4.0.0-alpha-58-g06e2034f
Git Commit Hash: 06e2034f4f8c58f04ce293180c1eaf515424a58e
Git Branch: master
UTC Build Time:  2019-09-17 02:36:29
```

**Comment by suzaku** [comment]
I encountered the same problem when running some integration tests depending on PD.

**Comment by rleungx** [comment]
Fixed via https://github.com/pingcap/pd/pull/1766.
